categories:
  - title: '⚠️ Breaking changes'
    label: 'BREAKING CHANGES'

  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    label: 'chore'

  - title: '📚 Documentation'
    label: 'documentation'

  - title: '🧪 Tests'
    label: 'tests'

  - title: '🏎 Optimizations'
    label: 'optimizations'

version-resolver:
  major:
    labels:
      - 'BREAKING CHANGES'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
  default: patch

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
template: |
  $CHANGES
